
version: '3.8'

services:
  job-matcher-api:
    build: .
    container_name: job-matcher-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG:-false}
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - job-matcher-network

  redis:
    image: redis:7-alpine
    container_name: job-matcher-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - job-matcher-network

  # Optional: Add nginx for production
  nginx:
    image: nginx:alpine
    container_name: job-matcher-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - job-matcher-api
    restart: unless-stopped
    networks:
      - job-matcher-network
    profiles:
      - production

volumes:
  redis_data:

networks:
  job-matcher-network:
    driver: bridge
